local dap = require("dap")
local dapgo = require('dap-go')
local dui = require("dapui")
local dapvtext = require("nvim-dap-virtual-text")

dapvtext.setup()
dui.setup()
dapgo.setup()

Nnoremap("<leader>dc", function()
    dui.open()
    dap.continue()
end)
Nnoremap("<F4>", dap.step_back)
Nnoremap("<F5>", dap.continue)
Nnoremap("<F7>", dap.step_into)
Nnoremap("<F6>", dap.step_over)
Nnoremap("<F10>", dap.restart)
Nnoremap("<leader>dr", function()
    dap.close()
    dui.open()
    dap.continue()
end)
Nnoremap("<leader>ds", function()
    dap.close()
    dui.close()
end)
Nnoremap("<leader>dt", dap.toggle_breakpoint)
