#!/bin/sh

.config/zsh/startupbspwm.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# to move and resize floating windows with my pointer and the super key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


# configurations in external rules file
# bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

# bspc rule -a Spotify desktop='^10'
bspc rule -a Emacs state=fullscreen
bash /home/kimil/.config/bspwm/bspwm_colors.sh &
