#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &

# Compositor picom
picom --config /home/kimil/.config/picom/picom.conf --backend glx -f -I 0.075 -O 0.075 &

# x-commands
# keyboard layout colemak and repetitive CapsLock/Backspace presses
setxkbmap us -variant colemak &

# sudo kmonad ~/testing/colemak-extend-iso.kbd &
xset r 66 &

# set tapping and natural scrolling on touchpad
xinput set-prop 12 "libinput Tapping Enabled" 1 &
xinput set-prop 12 "libinput Natural Scrolling Enabled" 1 &

# set cursor
xsetroot -cursor_name crosshair &

# set screen timeout
xset s 600 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock

# first add all the wallpapers then apply a random wallpaper including the theme
wpg -s ~/.config/wallpapers
# spicetify apply
pywal-discord -t abou
bash /home/kimil/.config/bspwm/bspwm_colors.sh &

# start clients like clipmenu, dunst, vpn etc 
clipmenud
dunst
mullvad-vpn

# copied from https://github.com/microsoft/vscode/issues/120392#issuecomment-814210643 for github auth in vscode/vscode-insiders for setting-sync etc
# init keyring
# eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
# export keyring
# export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
# exec dbus-launch dwm


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1'
bspc rule -a Opera dektop='^1'
