#!/bin/sh
firefox() {
	desktop=^3
}

discord() {
	desktop=^9
	follow=off

	bspc config ignore_ewmh_focus true
	nohup bash -c "sleep 2; bspc config ignore_ewmh_focus false" &
}

ranger() {
	state=floating
	rectangle=1200x800+0+0
	center=true
	layer=above
}

spotify() {
	state=tiled
	desktop=^10
}

case $instance.$class in
*.discord) discord ;;
*.Spotify) spotify ;;
Ranger.Alacritty) ranger ;;
.)
	case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
	spotify) spotify ;;
	esac
	;;
esac
