let g:neovide_refresh_rate=300
" let g:neovide_transparency=0.5
let g:neovide_cursor_vfx_mode = "pixiedust"
let g:neovide_cursor_animation_length=0.08
let g:neovide_cursor_trail_length=29.8
let g:neovide_cursor_vfx_particle_density=50.0
set guifont=JetBrainsMono_Nerd_Font_Mono:h8
" set guifont=Monoid_Nerd_Font_Mono:h7
" set guifont=VictorMono_Nerd_Font_Mono:h8
" set guifont=Inconsolata_Nerd_Font_Mono:h10
set guifont=CaskaydiaCove_Nerd_Font_Mono:h8
" set guifont=Hack_Nerd_Font_Mono:h7.5
