os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
gui:
  showIcons: true
git:
  showIcons: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
