# clipboard things
export CM_SELECTIONS="clipboard"
export CM_DEBUG=0
export CM_OUTPUT_CLIP=0
export CM_MAX_CLIPS=100
export CM_HISTLENGTH=20
export CM_LAUNCHER="rofi"

# xautolock stuff
export XSECURELOCK_SAVER="saver_xscreensaver"
export XSECURELOCK_SAVER="saver_mplayer"
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_PASSWORD_PROMPT="cursor"
export XSECURELOCK_COMPOSITE_OBSCURER=0

# editor to vim
export EDITOR="nvim"
export VISUAL="nvim"

export TERMINAL="$TERM"

# for wine idk why but it helps
export _JAVA_AWT_WM_NONPARENTING=1
export QT_STYLE_OVERRIDE=gtk2
